<br /><br /><center>View script for controller <b>Category</b> and script/action name <b>index</b></center>
<!--<?php echo __FILE__ ?>-->
<div id="doc">
    <div id="bd">

    </div><!-- #bd -->
    
    <div id="fb-root"></div>
</div><!-- #doc -->	
<!--END <?php echo __FILE__ ?>-->

<?php
$this->headTitle('Facebook Ui');
$this->usingYahooBaseGridCss();
$this->jQuery()
        ->setVersion('1.6.1')
        ->addJavascriptFile('http://connect.facebook.net/en_US/all.js')
        ->addJavascriptFile($this->baseUrl('js/jquery/jquery.cookie.js'))
        ->onLoadCaptureStart();
?>

var accessToken = '';
var appID = '139089182833103';
if (window.location.hash.length == 0) {
	var path = 'https://www.facebook.com/dialog/oauth?';
	var queryParams = [	'client_id=' + appID,
     					'redirect_uri=' + window.location,
     					'response_type=token'];
   	var query = queryParams.join('&');
   	var url = path + query;
	//window.open(url);
   	window.location = url;
} else {
	var accessToken = getToken();//window.location.hash.substring(1);
	var path = "https://graph.facebook.com/me?";
   	var queryParams = [accessToken, 'callback=displayUser'];
   	var query = queryParams.join('&');
   	var url = path + query;
   // use jsonp to call the graph
	var script = document.createElement('script');
	script.src = url;
	document.body.appendChild(script);        
}

function getUrlVars(href) {
    var vars = [], hash;
    var hashes = href.slice(href.indexOf('#') + 1).split('&');
    for(var i = 0; i < hashes.length; i++)
    {
        hash = hashes[i].split('=');
        vars.push(hash[0]);
        vars[hash[0]] = hash[1];
    }
    return vars;
}

function getToken() {
	return getUrlVars(location.hash)['access_token'];
}

	
FB.init({
    appId  : '139089182833103',
    status : true, // check login status
    cookie : true, // enable cookies to allow the server to access the session
	xfbml  : true  // parse XFBML
});
  
var publish = {
  method: 'feed',
  display: 'iframe',
  message: 'getting educated about Facebook Connect',
  name: 'Connect',
  caption: 'The Facebook Connect JavaScript SDK',
  description: (
      'A small JavaScript library that allows you to harness ' +
      'the power of Facebook, bringing the user\'s identity, ' +
      'social graph and distribution power to your site.'
  ),
  link: 'http://fbrell.com/',
  picture: 'http://fbrell.com/f8.jpg',
  actions: [
    { name: 'fbrell', link: 'http://fbrell.com/' }
  ],
  user_message_prompt: 'Share your thoughts about RELL'
};

FB.ui(publish, function(res){
	console.log(res);
});

function displayUser  (user) {
	console.log(user);
}
<?php $this->jQuery()->onLoadCaptureEnd() ?>

<?php $this->headScript()->captureStart()?>
function displayUser  (user) {
	console.log(user);
}
<?php $this->headScript()->captureEnd()?>