<!--<?php echo __FILE__ ?>-->
<div id="doc">
	<div id="top-position">&nbsp</div>
	<div id="bd">
		
		<p>Thủy thủ sống sót trên tàu Vinalines Queen đã về tới Việt Nam
			(Dân trí) - 18h30 ngày 4/1, thủy thủ Đậu Ngọc Hùng, người sống sót
			duy nhất trên chiếc tàu Vianlines Queen, từ Singapore đã về đến sân
			bay Nội Bài trên chuyến bay VN 660 của Hãng hàng không Quốc gia Việt
			Nam (Vietnam Airlines). >> Người thân thủy thủ sống sót trên tàu
			Vinalines Queen đẫm nước mắt >> Tàu Vinalines Queen bị chìm cùng 22
			thủy thủ Thủy thủ duy nhất của tàu Vinalines Queen sống sót đã trở về
			Việt Nam Sau khi làm thủ tục, 18h35, anh Hùng xuất hiện ở cửa ra quốc
			tế trong sự chờ đón của rất đông phóng viên báo chí và đại diện Tổng
			công ty Hàng hải Việt Nam. Người nhà anh Hùng không xuất hiện tại sân
			bay. Bị “quây” bởi cánh phóng viên, anh Hùng chỉ nói được đôi câu:
			“Tôi như từ cõi chết trở về. Hiện tôi chỉ có điều mong ước lớn nhất
			là tất cả các đồng đội tôi đều còn sống.” Anh Hùng trong vòng vây của
			báo chí tại sân bay Ngay sau đó, anh Hùng đã được đại diện Vinalines
			và Vinalines Shipping đưa lên chiếc ô tô 4 chỗ về trụ sở Vinalines ở
			Hà Nội lúc 18h50. Khi tàu Vinalines Queen bị chìm, anh Đậu Ngọc Hùng
			(SN 1980, quê Nghệ An) đã may mắn trèo lên được phao cứu sinh. Sau 5
			ngày lên đênh trên biển, anh Hùng được một tàu của Anh tên London
			Courage phát hiện, cứu sống tại địa điểm cách vị trí tàu chìm khoảng
			350km. Anh Hùng cho biết, con tàu Vinalines Queen đang chạy thì bị
			nghiêng về phía bên trái rồi chìm. Trong lúc khẩn nguy, tàu chỉ hạ
			được một phao cứu sinh bên phải và chỉ duy nhất anh Hùng là người may
			mắn leo lên được phao. Tại trụ sở của Vinalines, thủy thủ Đậu Ngọc
			Hùng nghẹn ngào kể lại giây phút con tàu gặp nạn Trước đó, 7h ngày
			25/12, tàu Vinalines Queen (thuộc Công ty vận tải biển Vinalines -
			Vinalines Shipping, Tổng Công ty hàng hải Việt Nam) đang thực hiện
			hành trình đến tọa độ 20 độ vĩ Bắc - 123,47 độ kinh Đông (phía
			Đông-Bắc Đảo Luzon - Philippines) đã phát đi thông báo bị nghiêng 180
			và mất liên lạc. Sau những nỗ lực tìm kiếm, đến ngày 30/12, Trung tâm
			Phối hợp tìm kiếm cứu nạn hàng hải Việt Nam chính thức thông báo, tàu
			Vinalines Queen bị chìm. Dân trí sẽ tiếp tục cập nhật thông tin về vụ
			việc này. Tiến Nguyên</p>
		<p>Thủy thủ sống sót trên tàu Vinalines Queen đã về tới Việt Nam
			(Dân trí) - 18h30 ngày 4/1, thủy thủ Đậu Ngọc Hùng, người sống sót
			duy nhất trên chiếc tàu Vianlines Queen, từ Singapore đã về đến sân
			bay Nội Bài trên chuyến bay VN 660 của Hãng hàng không Quốc gia Việt
			Nam (Vietnam Airlines). >> Người thân thủy thủ sống sót trên tàu
			Vinalines Queen đẫm nước mắt >> Tàu Vinalines Queen bị chìm cùng 22
			thủy thủ Thủy thủ duy nhất của tàu Vinalines Queen sống sót đã trở về
			Việt Nam Sau khi làm thủ tục, 18h35, anh Hùng xuất hiện ở cửa ra quốc
			tế trong sự chờ đón của rất đông phóng viên báo chí và đại diện Tổng
			công ty Hàng hải Việt Nam. Người nhà anh Hùng không xuất hiện tại sân
			bay. Bị “quây” bởi cánh phóng viên, anh Hùng chỉ nói được đôi câu:
			“Tôi như từ cõi chết trở về. Hiện tôi chỉ có điều mong ước lớn nhất
			là tất cả các đồng đội tôi đều còn sống.” Anh Hùng trong vòng vây của
			báo chí tại sân bay Ngay sau đó, anh Hùng đã được đại diện Vinalines
			và Vinalines Shipping đưa lên chiếc ô tô 4 chỗ về trụ sở Vinalines ở
			Hà Nội lúc 18h50. Khi tàu Vinalines Queen bị chìm, anh Đậu Ngọc Hùng
			(SN 1980, quê Nghệ An) đã may mắn trèo lên được phao cứu sinh. Sau 5
			ngày lên đênh trên biển, anh Hùng được một tàu của Anh tên London
			Courage phát hiện, cứu sống tại địa điểm cách vị trí tàu chìm khoảng
			350km. Anh Hùng cho biết, con tàu Vinalines Queen đang chạy thì bị
			nghiêng về phía bên trái rồi chìm. Trong lúc khẩn nguy, tàu chỉ hạ
			được một phao cứu sinh bên phải và chỉ duy nhất anh Hùng là người may
			mắn leo lên được phao. Tại trụ sở của Vinalines, thủy thủ Đậu Ngọc
			Hùng nghẹn ngào kể lại giây phút con tàu gặp nạn Trước đó, 7h ngày
			25/12, tàu Vinalines Queen (thuộc Công ty vận tải biển Vinalines -
			Vinalines Shipping, Tổng Công ty hàng hải Việt Nam) đang thực hiện
			hành trình đến tọa độ 20 độ vĩ Bắc - 123,47 độ kinh Đông (phía
			Đông-Bắc Đảo Luzon - Philippines) đã phát đi thông báo bị nghiêng 180
			và mất liên lạc. Sau những nỗ lực tìm kiếm, đến ngày 30/12, Trung tâm
			Phối hợp tìm kiếm cứu nạn hàng hải Việt Nam chính thức thông báo, tàu
			Vinalines Queen bị chìm. Dân trí sẽ tiếp tục cập nhật thông tin về vụ
			việc này. Tiến Nguyên</p>
		<p>Thủy thủ sống sót trên tàu Vinalines Queen đã về tới Việt Nam
			(Dân trí) - 18h30 ngày 4/1, thủy thủ Đậu Ngọc Hùng, người sống sót
			duy nhất trên chiếc tàu Vianlines Queen, từ Singapore đã về đến sân
			bay Nội Bài trên chuyến bay VN 660 của Hãng hàng không Quốc gia Việt
			Nam (Vietnam Airlines). >> Người thân thủy thủ sống sót trên tàu
			Vinalines Queen đẫm nước mắt >> Tàu Vinalines Queen bị chìm cùng 22
			thủy thủ Thủy thủ duy nhất của tàu Vinalines Queen sống sót đã trở về
			Việt Nam Sau khi làm thủ tục, 18h35, anh Hùng xuất hiện ở cửa ra quốc
			tế trong sự chờ đón của rất đông phóng viên báo chí và đại diện Tổng
			công ty Hàng hải Việt Nam. Người nhà anh Hùng không xuất hiện tại sân
			bay. Bị “quây” bởi cánh phóng viên, anh Hùng chỉ nói được đôi câu:
			“Tôi như từ cõi chết trở về. Hiện tôi chỉ có điều mong ước lớn nhất
			là tất cả các đồng đội tôi đều còn sống.” Anh Hùng trong vòng vây của
			báo chí tại sân bay Ngay sau đó, anh Hùng đã được đại diện Vinalines
			và Vinalines Shipping đưa lên chiếc ô tô 4 chỗ về trụ sở Vinalines ở
			Hà Nội lúc 18h50. Khi tàu Vinalines Queen bị chìm, anh Đậu Ngọc Hùng
			(SN 1980, quê Nghệ An) đã may mắn trèo lên được phao cứu sinh. Sau 5
			ngày lên đênh trên biển, anh Hùng được một tàu của Anh tên London
			Courage phát hiện, cứu sống tại địa điểm cách vị trí tàu chìm khoảng
			350km. Anh Hùng cho biết, con tàu Vinalines Queen đang chạy thì bị
			nghiêng về phía bên trái rồi chìm. Trong lúc khẩn nguy, tàu chỉ hạ
			được một phao cứu sinh bên phải và chỉ duy nhất anh Hùng là người may
			mắn leo lên được phao. Tại trụ sở của Vinalines, thủy thủ Đậu Ngọc
			Hùng nghẹn ngào kể lại giây phút con tàu gặp nạn Trước đó, 7h ngày
			25/12, tàu Vinalines Queen (thuộc Công ty vận tải biển Vinalines -
			Vinalines Shipping, Tổng Công ty hàng hải Việt Nam) đang thực hiện
			hành trình đến tọa độ 20 độ vĩ Bắc - 123,47 độ kinh Đông (phía
			Đông-Bắc Đảo Luzon - Philippines) đã phát đi thông báo bị nghiêng 180
			và mất liên lạc. Sau những nỗ lực tìm kiếm, đến ngày 30/12, Trung tâm
			Phối hợp tìm kiếm cứu nạn hàng hải Việt Nam chính thức thông báo, tàu
			Vinalines Queen bị chìm. Dân trí sẽ tiếp tục cập nhật thông tin về vụ
			việc này. Tiến Nguyên</p>
		<p>Thủy thủ sống sót trên tàu Vinalines Queen đã về tới Việt Nam
			(Dân trí) - 18h30 ngày 4/1, thủy thủ Đậu Ngọc Hùng, người sống sót
			duy nhất trên chiếc tàu Vianlines Queen, từ Singapore đã về đến sân
			bay Nội Bài trên chuyến bay VN 660 của Hãng hàng không Quốc gia Việt
			Nam (Vietnam Airlines). >> Người thân thủy thủ sống sót trên tàu
			Vinalines Queen đẫm nước mắt >> Tàu Vinalines Queen bị chìm cùng 22
			thủy thủ Thủy thủ duy nhất của tàu Vinalines Queen sống sót đã trở về
			Việt Nam Sau khi làm thủ tục, 18h35, anh Hùng xuất hiện ở cửa ra quốc
			tế trong sự chờ đón của rất đông phóng viên báo chí và đại diện Tổng
			công ty Hàng hải Việt Nam. Người nhà anh Hùng không xuất hiện tại sân
			bay. Bị “quây” bởi cánh phóng viên, anh Hùng chỉ nói được đôi câu:
			“Tôi như từ cõi chết trở về. Hiện tôi chỉ có điều mong ước lớn nhất
			là tất cả các đồng đội tôi đều còn sống.” Anh Hùng trong vòng vây của
			báo chí tại sân bay Ngay sau đó, anh Hùng đã được đại diện Vinalines
			và Vinalines Shipping đưa lên chiếc ô tô 4 chỗ về trụ sở Vinalines ở
			Hà Nội lúc 18h50. Khi tàu Vinalines Queen bị chìm, anh Đậu Ngọc Hùng
			(SN 1980, quê Nghệ An) đã may mắn trèo lên được phao cứu sinh. Sau 5
			ngày lên đênh trên biển, anh Hùng được một tàu của Anh tên London
			Courage phát hiện, cứu sống tại địa điểm cách vị trí tàu chìm khoảng
			350km. Anh Hùng cho biết, con tàu Vinalines Queen đang chạy thì bị
			nghiêng về phía bên trái rồi chìm. Trong lúc khẩn nguy, tàu chỉ hạ
			được một phao cứu sinh bên phải và chỉ duy nhất anh Hùng là người may
			mắn leo lên được phao. Tại trụ sở của Vinalines, thủy thủ Đậu Ngọc
			Hùng nghẹn ngào kể lại giây phút con tàu gặp nạn Trước đó, 7h ngày
			25/12, tàu Vinalines Queen (thuộc Công ty vận tải biển Vinalines -
			Vinalines Shipping, Tổng Công ty hàng hải Việt Nam) đang thực hiện
			hành trình đến tọa độ 20 độ vĩ Bắc - 123,47 độ kinh Đông (phía
			Đông-Bắc Đảo Luzon - Philippines) đã phát đi thông báo bị nghiêng 180
			và mất liên lạc. Sau những nỗ lực tìm kiếm, đến ngày 30/12, Trung tâm
			Phối hợp tìm kiếm cứu nạn hàng hải Việt Nam chính thức thông báo, tàu
			Vinalines Queen bị chìm. Dân trí sẽ tiếp tục cập nhật thông tin về vụ
			việc này. Tiến Nguyên</p>
			<a href='#top-position' id="back-to-top" >Back to top</a>
	</div>
	<!-- #bd -->
	<div id="fb-root"></div>
</div>
<!-- #doc -->
<!--END <?php echo __FILE__ ?>-->

<?php $this->headStyle()->captureStart();?>
#back-to-top {
	position:fixed;
	left:100px;
	top:150px;
	display:none;
}
<?php $this->headStyle()->captureEnd();?>

<?php
$this->headTitle('CyApi Test');
$this->usingYahooBaseGridCss();
$this->headLink()->appendStylesheet($this->baseUrl('js/jquery/qunit/qunit.css'));
$this->headLink()->appendStylesheet($this->baseUrl('css/default/index.css'));

$this->jQuery()
        ->setVersion('1.6.1')
        ->setLocalPath($this->baseUrl('lib/jquery/1.6.1/jquery.min.js'))
        ->onLoadCaptureStart();
?>
$(window).scroll(function () {
    /*if ( $(window).width() > 500) {*/
        if ($(window).scrollTop() > 100) {
            $('#back-to-top').fadeIn('fast');
        } else {
            $('#back-to-top').fadeOut('fast');
        }
    /*}*/
});
$(window).scroll();
<?php $this->jQuery()->onLoadCaptureEnd() ?>